---
- name: 'install tftp, nginx for serving kickstart configuration'
  package:
    name:
      - tftp-server
      - nginx

- name: 'ensure /var/www'
  file:
    path: '/var/www'
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: 'ensure /var/www/html'
  file:
    path: '/var/www/html'
    state: directory
    mode: '0755'
    owner: root
    group: nginx

- name: 'nginx configuration'
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: 'reload nginx'

- name: 'Ensure nginx is running'
  service:
    name: nginx
    state: started
    enabled: true

- name: Enable tftp server socket
  systemd:
    name: tftp.socket
    state: started
    enabled: true

- name: 'Create UEFI PXE-boot configuration directory'
  file:
    mode: '0755'
    path: '/var/lib/tftpboot/uefi'
    state: directory

- name: 'Download GRUB EFI binary'
  get_url:
    dest: '/var/lib/tftpboot/uefi/grubx64.efi'
    url: '{{ centos_8_kickstart_mirror | mandatory }}/EFI/BOOT/grubx64.efi'

- name: 'Download CentOS 8 kernel'
  get_url:
    dest: '/var/lib/tftpboot/ks-centos-8-vmlinuz'
    url: '{{ centos_8_kickstart_mirror }}/images/pxeboot/vmlinuz'

- name: 'Download CentOS 8 initrd'
  get_url:
    dest: '/var/lib/tftpboot/ks-centos-8-initrd.img'
    url: '{{ centos_8_kickstart_mirror }}/images/pxeboot/initrd.img'
